[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.9"
dependencies = [
    "aiotaskq @ file://${PROJECT_DIR}/",
    "celery >= 5.2.0, < 5.3.0",
    "redis >= 4.3.4, < 4.4.0",
]
name = "sample_apps"
version = "0.0.0"
readme = "README.md"
description = "A collection of sample apps to test aiotaskq against Celery"
authors = [
    {name = "Imran Ariffin", email = "ariffin.imran@gmail.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = { file = "LICENSE" }
