[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.9"
dependencies = [
    "celery >= 5.2.0, < 5.3.0",
    "aiotaskq @ file://${PROJECT_DIR}/",
]
name = "simple_app"
version = "0.0.0"
readme = "README.md"
description = "A simple app using Celery"
authors = [
    {name = "Imran Ariffin", email = "ariffin.imran@gmail.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = { file = "LICENSE" }
