name: Check Docs
on:
  pull_request:
    branches:
    - main
jobs:
  check_docs:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: ./update-docs.sh
