name: coverage
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  check_guides:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker-compose -f ./docker-compose.yml up --detach redis
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10.x"
    - run: source ./activate.sh
    - run: pip install --upgrade pip
    - run: pip install -e .[dev]
    - run: pip freeze
    - run: ./docs/check-guides.sh

  run_unit_tests:
    needs: check_guides
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: docker-compose -f ./docker-compose.yml up --detach redis
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10.x"
    - run: source ./activate.sh
    - run: pip install --upgrade pip
    - run: pip install -e .[dev]
    - run: pip freeze
    - run: ./test.sh
    - uses: codecov/codecov-action@v3.1.0
