name: publish
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  publish:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10.x"
    - run: pip install --upgrade pip
    - run: pip install -e .[dev]
    - run: pip freeze
    - name: Publish
      env:
        PYPI_TOKEN_DEV: ${{ secrets.PYPI_TOKEN_DEV }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: ./publish.sh
