name: pylint
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10.x"
    - run: ./lint.sh
