name: Run Checks

on:
  pull_request:
    branches:
    - main

jobs:
  run_unit_tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f ./docker-compose.yml up --detach redis

    - uses: actions/setup-python@v3
      with:
        python-version: "3.10.x"

    - name: Setup Python & Run Tests
      run: |
        echo "Using python " $(python --version)
        python -m venv .venv
        source ./.venv/bin/activate
        pip install --upgrade pip
        pip install -e .
        pip freeze
        python ./src/aiotaskq/tests/integration_test.py
